# Generated by Django 2.1.3 on 2018-11-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPhoneNum', models.CharField(max_length=13)),
                ('userName', models.CharField(max_length=16)),
                ('userPw', models.CharField(max_length=16)),
                ('userAge', models.IntegerField()),
            ],
        ),
    ]
